### ISSUE TITLE
HKCategoryTypeIdentifier.mindfulSession not supported

### ISSUE THREAD

**Issue by schilken** [VictorKachalov/health_kit_reporter#10]
It's not in the enum CategoryType and I think It's also not supported in the cocoapod.

I saw that you are updating both synchronously, maybe you can add some missing types when you get a chance.

Thanks
Alfred

**Comment by VictorKachalov** [comment]
Hi @schilken ,

Thank you very much that you spotted it. For sure I will add this in a next version

**Comment by VictorKachalov** [comment]
Hi @schilken ,

I have expanded the original CategoryType Enum with cases which were not yet covered. It is in original CcocaPod https://github.com/VictorKachalov/HealthKitReporter

In order to use it in the Flutter plugin, you need to update the Podfile in your Flutter project.
You should see that the plugin has updated the dependency HealthKitReporter to version 1.3.3

**Comment by schilken** [comment]
Hi Victor,
thanks for your quick reaction. I saw there are now a lot of added entries in the pod. Even 'runnyNose' is supported by HealthKit - funny.

But the flutter plugin also needs a change, or do I get that wrong? Will you do that in next days?

Regards
Alfred

**Comment by VictorKachalov** [comment]
Hi @schilken,

Yes true, you have the point, I totally forgot about this, made a change in Flutter code as well, please check the version 1.0.8

Regards,
Victor

**Comment by schilken** [comment]
Hi @VictorKachalov, thanks again. Now with version 1.0.8 my query for CategoryType.mindfulSession works!
