### ISSUE TITLE
Support retrieving voltage measurements for ECG records

### ISSUE THREAD

**Issue by krml19** [VictorKachalov/health_kit_reporter#39]
**Is your feature request related to a problem? Please describe.**
There is no option to get a voltage measurement for ECG records. 

**Describe the solution you'd like**
Modify the `Electrocardiogram` class to include voltage measurement samples.

**Describe alternatives you've considered**
Add additional platform method to query voltage measurement samples.

**Additional context**
At the moment, the library provides a way of retrieving ECG records from Apple Health Kit which is great but it does not allow to get the underlying voltage measurements. Therefore, the usage of this feature is limited.

**Comment by VictorKachalov** [comment]
Hi @krml19 

Please check the version 2.0.3. ECG values can be extracted with or without voltage measurements by demand. This approach is because of the amount of voltage measurements. They can reach to 15k values

The ECG topic is very specific and If this package really helps you and is worthy to be maintained further, I would appreciate any financial support to buy more devices
