### ISSUE TITLE
Wrong indicate git revision of 1.0.6?

### ISSUE THREAD

**Issue by YasufumiMuranaka** [VictorKachalov/health_kit_reporter#8]
**Describe the bug**
Wrong indicate git revision of 1.0.6?

**To Reproduce**

**Screenshots**

<img width="1077" alt="スクリーンショット 2021-01-17 10 01 38" src="https://user-images.githubusercontent.com/33305925/104828409-68c08a00-58ac-11eb-95fb-7af9ab31170a.png">

Your example is No Error.
<img width="1060" alt="スクリーンショット 2021-01-17 10 02 14" src="https://user-images.githubusercontent.com/33305925/104828414-7118c500-58ac-11eb-9fa6-ee34d86a8c22.png">

**Additional context**

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.5, on macOS 11.1 20C69 darwin-arm, locale ja-JP)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.52.1)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.

```

**Comment by VictorKachalov** [comment]
Thank you for your report.

I was able to reproduce the issue. If I try to fetch from the repo providing the version instead of using path, I got errors in main example app... The error is related to changes I made for PrefferedUnit. This was because I made some changes, pushed to the GitHub, but not updated the plugin on pub dev. 

Made an update, the actual version is 1.0.7. Please check

**Comment by YasufumiMuranaka** [comment]
Hi,
It was successfully ran by 1.0.7.
Thank you for your prompt response.

**Comment by YasufumiMuranaka** [comment]
Hi,
It was successfully ran via 1.0.7.
Thank you for your prompt response.
